### PR TITLE
Add image zoom in feature

### PR DESCRIPTION
**Pull request by IamJoyson**

### CODE REVIEW

**Comment by hs-saunved** [comment]
@IamJoyson 
Can we make the background darker instead of lighter when we click on images? I think it will help most of the images stand out (especially since our dashboard is light themed).

Also, if we can add an offset at the top for the images (to account for the top bar), that would be nice. Otherwise some large images are getting hidden beneath the top bar after they are zoomed.

One more thing I noticed with this plugin is that it doesn't let you zoom further into images once you click on them. If you scroll or swipe, the image goes back into its slot. It would be nice if we could zoom into the image further after clicking it. But if the plugin is not providing this, then we can keep it as a backlog item.

**Comment by IamJoyson** [comment]
> Can we make the background darker instead of lighter when we click on images? I think it will help most of the images stand out (especially since our dashboard is light themed).

I made the background color black for both themes. 


> Also, if we can add an offset at the top for the images (to account for the top bar), that would be nice. Otherwise, some large images are getting hidden beneath the top bar after they are zoomed in.

There was an option to add a margin to the image, I gave 20px.



> One more thing I noticed with this plugin is that it doesn't let you zoom further into images once you click on them. If you scroll or swipe, the image goes back into its slot. It would be nice if we could zoom into the image further after clicking it. But if the plugin is not providing this, then we can keep it as a backlog item.

yes the js package `medium-zoom` which is the js package it self does not support zooming in. https://github.com/francoischalifour/medium-zoom

**Comment by hs-saunved** [comment]
All the new changes look good to me. The desktop and tablet experience is definitely improved by this!

However, I feel like the experience on mobile may be hampered by this plugin. The images will always stay the same size (since we use full width images anyway) on mobile devices. If there is a way to disable this feature on mobile, we should do it.

No issues if this is not possible though.

**Review by jaydeep-helpshift — APPROVED** [review]

**Comment by IamJoyson** [comment]
I explored the options but I could not find any solution to disable this on mobile. We can merge and have this in backlog to improve it on mobile.

**Pull request merged**
