### PR TITLE
Update Legacy EoL notices

### PR DESCRIPTION
**Pull request by hs-saunved**

### CODE REVIEW

**Review by jaydeep-helpshift — APPROVED** [review]

**Review by helpshift-ps — COMMENTED** [review]
Is it possible to add the warning on the landing pages as well? 

- https://helpshift-docs-git-update-eol-notices-helpshift-dev-team.vercel.app/android/
- https://helpshift-docs-git-update-eol-notices-helpshift-dev-team.vercel.app/ios/

Also, plugin pages need these warning.

**Comment by hs-saunved** [comment]
@helpshift-ps It is not possible to add this warning on landing pages since these are auto-generated. There may be a workaround, but I don't think it's straightforward.

Should I update all the plugin pages or only those that have an SDK X alternative available?

**Comment by helpshift-ps** [comment]
> 

We should add the note to all plugin pages. This is the status of legacy SDK plugins:
* Unity - SDK X plugin exists for this
* Cocos - SDK X plugin is coming up soon
* Xamarin - SDK X plugin is coming up soon

So, it's okay to publish the note for these pages, too. Keeping @helpshift-vishal in the loop.

**Comment by helpshift-vishal** [comment]
@helpshift-ps For the ones where SDK X exists, in the legacy SDK pages, along with the notice text, better to give them the hyperlink , which will re-direct them to SDK x page of that.

**Comment by hs-saunved** [comment]
@helpshift-vishal Thanks for the suggestion. Adding separate hyperlinks based on the SDK for all the plugins will take slightly more time. I can create an issue to tackle this as a backlog item. For now, we can redirect users to the main landing page which shows the Latest SDKs at the top (for the SDKs that @helpshift-ps has mentioned).

Let me know if this works for you. Thanks!

**Review by jaydeep-helpshift — APPROVED** [review]

**Review by helpshift-ps — APPROVED** [review]

**Pull request merged**
